[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"

[build]
target = "riscv32i-unknown-none-elf"

[package.metadata.cargo-xbuild]
linker-script = "link.x"
